title: Sarah Robinson
description: Sarah Robinson PhD Candidate in Economics at University of California Santa Barbara Econ UCSB 
tagline: PhD Candidate UCSB Economics
subtitle1: PhD Candidate in Economics
subtitle2: University of California Santa Barbara
show_downloads: true
google_analytics: G-VGDK4HLWCX
theme: jekyll-theme-dinky