title: Sarah Robinson
description: PhD Candidate UCSB Economics
subtitle1: PhD&nbsp;Candidate in&nbsp;Economics
subtitle2: University&nbsp;of&nbsp;California Santa&nbsp;Barbara
show_downloads: true
google_analytics: UA-200546079-1
theme: jekyll-theme-dinky
url: "https://www.s-robinson.com"
plugins:
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap