title: Sarah Robinson
description: PhD Candidate UCSB Economics
subtitle1: PhD Candidate in Economics
subtitle2: University of California Santa Barbara
show_downloads: true
google_analytics: UA-200546079-1
theme: jekyll-theme-dinky
url: "https://www.s-robinson.com"
plugins:
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap