title: Sarah Robinson
description: PhD Candidate UCSB Economics
subtitle1: PhD&nbsp;Candidate in&nbsp;Economics
subtitle2: University&nbsp;of&nbsp;California Santa&nbsp;Barbara
google_analytics: G-27LF2RKDVX
remote_theme: pages-themes/dinky@v0.2.0
url: "https://www.s-robinson.com"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap