title: Sarah Robinson
description: Claremont McKenna College
google_analytics_custom: G-27LF2RKDVX
remote_theme: pages-themes/dinky@v0.2.0
url: "https://www.s-robinson.com"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap