title: Sarah Robinson
description: PhD Student in Economics at University of California, Santa Barbara
subtitle1: PhD Candidate in Economics
subtitle2: University of California Santa Barbara
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky